package com.bank_web_app.backend.loansense.dto.response;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public record LoanTypeDetailResponse(
	Long loansenseEvaluationId,
	Long loanResultId,
	String loanType,
	String loanTypeKey,
	String loanTypeLabel,
	String eligibilityStatus,
	String eligibilityLabel,
	BigDecimal recommendedMaxAmount,
	BigDecimal estimatedEmi,
	BigDecimal interestRate,
	Integer tenureMonths,
	Integer policyMinTenureMonths,
	Integer policyMaxTenureMonths,
	String tenureLabel,
	Integer customerAge,
	BigDecimal assetValue,
	BigDecimal monthlyIncome,
	BigDecimal totalExistingLoanEmi,
	BigDecimal creditCardMinPayment,
	BigDecimal leasingHirePurchasePayment,
	BigDecimal tmdo,
	Integer missedPaymentsCount,
	BigDecimal dbr,
	BigDecimal policyMaxDbrRatio,
	BigDecimal maxAllowedEmi,
	BigDecimal availableEmiCapacity,
	String riskLevel,
	String riskLabel,
	BigDecimal riskMultiplier,
	String riskAdjustmentDescription,
	BigDecimal policyMinIncomeRequired,
	Integer policyMinAge,
	Integer policyMaxAge,
	BigDecimal policyMaxFinancePercentage,
	String policyStatus,
	String decisionReason,
	LocalDateTime createdAt
) {
}
