package com.bank_web_app.backend.user.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import java.math.BigDecimal;

@Schema(name = "UserRegistrationStepOneRequest", description = "Step 1 payload for role-aware user registration.")
public record UserRegistrationStepOneRequest(
@Schema(description = "Customer first name", example = "John", requiredMode = Schema.RequiredMode.REQUIRED)
@NotBlank(message = "First name is required.")
@Size(min = 2, max = 100, message = "First name must be between 2 and 100 characters.")
String firstName,
@Schema(description = "Customer last name", example = "Doe", requiredMode = Schema.RequiredMode.REQUIRED)
@NotBlank(message = "Last name is required.")
@Size(min = 2, max = 100, message = "Last name must be between 2 and 100 characters.")
String lastName,
@Schema(description = "National identity card number", example = "200012345678", requiredMode = Schema.RequiredMode.REQUIRED)
@NotBlank(message = "NIC is required.")
@Size(max = 20, message = "NIC must not exceed 20 characters.")
String nic,
@Schema(description = "Date of birth in ISO format (yyyy-MM-dd)", example = "2000-03-15", requiredMode = Schema.RequiredMode.REQUIRED)
@NotBlank(message = "Date of birth is required.")
@Pattern(regexp = "^\\d{4}-\\d{2}-\\d{2}$", message = "DOB must be in yyyy-MM-dd format.")
String dob,
@Schema(description = "Email address", example = "john.doe@bank.com", requiredMode = Schema.RequiredMode.REQUIRED)
@NotBlank(message = "Email is required.")
@Email(message = "Enter a valid email address.")
@Size(max = 100, message = "Email must not exceed 100 characters.")
String email,
@Schema(description = "Mobile number", example = "+94771234567", requiredMode = Schema.RequiredMode.REQUIRED)
@NotBlank(message = "Mobile is required.")
@Size(max = 20, message = "Mobile must not exceed 20 characters.")
String mobile,
@Schema(description = "Province", example = "Western", requiredMode = Schema.RequiredMode.REQUIRED)
@NotBlank(message = "Province is required.")
String province,
@Schema(description = "Address", example = "123, Main Street, Colombo", requiredMode = Schema.RequiredMode.REQUIRED)
@NotBlank(message = "Address is required.")
String address,
@Schema(description = "Username for account login", example = "john.doe.2000", requiredMode = Schema.RequiredMode.REQUIRED)
@NotBlank(message = "Username is required.")
@Size(min = 4, max = 50, message = "Username must be between 4 and 50 characters.")
String username,
@Schema(description = "Raw password from frontend.", example = "StrongPass123", requiredMode = Schema.RequiredMode.REQUIRED)
@NotBlank(message = "Password is required.")
@Size(min = 8, max = 255, message = "Password must be between 8 and 255 characters.")
String password,
@Schema(description = "Client-side password confirmation", example = "StrongPass123", requiredMode = Schema.RequiredMode.REQUIRED)
@NotBlank(message = "Confirm password is required.")
String confirmPassword,
@Schema(description = "Legacy bank account field retained for backward compatibility.", example = "123456789")
@Positive(message = "Bank account must be a positive integer.")
Integer bankAccount,
@Schema(description = "Branch id kept for backward compatibility. BANK_CUSTOMER flow resolves branch from the authenticated officer.", example = "1")
@Positive(message = "Branch id must be a positive number.")
Long branchId,
@Schema(description = "Officer id kept for backward compatibility. BANK_CUSTOMER flow resolves officer from the authenticated user.", example = "5")
@Positive(message = "Officer id must be a positive number.")
Long officerId,
@Schema(description = "Legacy employee code field. BANK_OFFICER employee code is auto-generated by backend.", example = "EMP-BO-00001")
@Size(max = 50, message = "Employee code must not exceed 50 characters.")
String employeeCode,
@Schema(description = "Admin user id who created this bank officer.", example = "2")
@Positive(message = "Created-by admin user id must be a positive number.")
Long createdByAdminUserId,
@Schema(description = "Customer code override. If empty, service auto-generates one.", example = "BC-000123")
@Size(max = 50, message = "Customer code must not exceed 50 characters.")
String customerCode,
@Schema(description = "Account number used to look up or create the account row, then retrieve accountId.", example = "20010010012345")
@Size(max = 30, message = "Account number must not exceed 30 characters.")
String accountNumber,
@Schema(description = "Account type for BANK_CUSTOMER. Defaults to SAVINGS.", example = "SAVINGS")
@Size(max = 30, message = "Account type must not exceed 30 characters.")
String accountType,
@Schema(description = "Optional opening balance for BANK_CUSTOMER account.", example = "0.00")
@DecimalMin(value = "0.00", message = "Opening balance cannot be negative.")
BigDecimal openingBalance
) {
}
