-- DEVELOPMENT/STAGING ONLY. Run after mock-logins.sql and the five mock bank
-- customers have been seeded. Inserts related beneficiaries and completed
-- transactions; OTP and audit records are intentionally generated by the app.

WITH seed (username, beneficiary_account_no, nick_name, remark) AS (
    VALUES
        ('bank.customer.01', '999000000102', 'Nimal Silva', 'Mock beneficiary'),
        ('bank.customer.02', '999000000103', 'Sahan Fernando', 'Mock beneficiary'),
        ('bank.customer.03', '999000000104', 'Tharindu Jayasinghe', 'Mock beneficiary'),
        ('bank.customer.04', '999000000105', 'Isuru Kumarasinghe', 'Mock beneficiary'),
        ('bank.customer.05', '999000000101', 'Kasun Perera', 'Mock beneficiary')
)
INSERT INTO bank_customer_beneficiaries (
    bank_customer_id, beneficiary_account_no, nick_name, remark, created_at, updated_at
)
SELECT
    customer.bank_customer_id,
    seed.beneficiary_account_no,
    seed.nick_name,
    seed.remark,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM seed
JOIN users user_record ON user_record.username = seed.username
JOIN bank_customers customer ON customer.user_id = user_record.user_id
WHERE NOT EXISTS (
    SELECT 1
    FROM bank_customer_beneficiaries existing
    WHERE existing.bank_customer_id = customer.bank_customer_id
      AND existing.beneficiary_account_no = seed.beneficiary_account_no
);

WITH seed (username, receiver_account_no, receiver_name, amount, remark, reference_no, transaction_date) AS (
    VALUES
        ('bank.customer.01', '999000000102', 'Nimal Silva', 2500.00, 'Mock utility payment', 'MOCK-TXN-0001', CURRENT_TIMESTAMP - INTERVAL '5 days'),
        ('bank.customer.02', '999000000103', 'Sahan Fernando', 7500.00, 'Mock rent transfer', 'MOCK-TXN-0002', CURRENT_TIMESTAMP - INTERVAL '4 days'),
        ('bank.customer.03', '999000000104', 'Tharindu Jayasinghe', 4200.00, 'Mock grocery transfer', 'MOCK-TXN-0003', CURRENT_TIMESTAMP - INTERVAL '3 days'),
        ('bank.customer.04', '999000000105', 'Isuru Kumarasinghe', 9800.00, 'Mock education payment', 'MOCK-TXN-0004', CURRENT_TIMESTAMP - INTERVAL '2 days'),
        ('bank.customer.05', '999000000101', 'Kasun Perera', 3100.00, 'Mock transport payment', 'MOCK-TXN-0005', CURRENT_TIMESTAMP - INTERVAL '1 day')
)
INSERT INTO bank_customer_transactions (
    bank_customer_id, sender_account_no, receiver_account_no, receiver_name,
    amount, remark, reference_no, status, otp_verified, expense_tracking_enabled,
    transaction_date, created_at, updated_at
)
SELECT
    customer.bank_customer_id,
    sender_account.account_number,
    seed.receiver_account_no,
    seed.receiver_name,
    seed.amount,
    seed.remark,
    seed.reference_no,
    'SUCCESS',
    TRUE,
    FALSE,
    seed.transaction_date,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM seed
JOIN users user_record ON user_record.username = seed.username
JOIN bank_customers customer ON customer.user_id = user_record.user_id
JOIN accounts sender_account ON sender_account.account_id = customer.account_id
WHERE NOT EXISTS (
    SELECT 1
    FROM bank_customer_transactions existing
    WHERE existing.reference_no = seed.reference_no
);
