package com.bank_web_app.backend.notification.entity;

public enum NotificationType {
	NEW_CUSTOMER_SUMMARY,
	CUSTOMER_ASSIGNED,
	BRANCH_STATUS_CHANGED,
	OFFICER_ACCOUNT_STATUS_CHANGED,
	SYSTEM_NOTICE,
	SPENDIQ_TRANSFER_IMPORTED,
	SPENDIQ_BUDGET_THRESHOLD,
	SPENDIQ_MONTHLY_SUMMARY,
	CREDITLENS_RESULT_AVAILABLE,
	CREDITLENS_PORTFOLIO_ATTENTION,
	LOANSENSE_RESULT_AVAILABLE,
	LOANSENSE_PORTFOLIO_ATTENTION,
	LOAN_POLICY_CHANGED,
	FINANCIAL_DETAILS_MISSING,
	MONTHLY_FINANCIAL_REVIEW_DUE
}
