package com.bank_web_app.backend.notification.event;

public enum NotificationEventType {
	ADMIN_NEW_CUSTOMER,
	PUBLIC_FINANCIAL_DETAILS_REQUIRED,
	BANK_CUSTOMER_ASSIGNED,
	BRANCH_STATUS_CHANGED,
	OFFICER_STATUS_CHANGED,
	LOAN_POLICY_CHANGED,
	SPENDIQ_TRANSFER_IMPORTED,
	SPENDIQ_BUDGET_THRESHOLD,
	CREDITLENS_EVALUATED,
	LOANSENSE_EVALUATED
}
